import {
  siNextdotjs,
  siTailwindcss,
  siPostgresql,
  siPrisma,
  siDrizzle,
  siNeon,
  siDatagrip,
  siCursor,
  siTypescript,
  siReact,
  siNodedotjs,
  siGit,
  siGithub,
  siVercel,
  siFigma,
  siSupabase,
  siFirebase,
  siMongodb,
  siRedis,
  siDocker,
  siPython,
  siRust,
  siSwift,
  siKubernetes,
  siLinux,
  siVite,
  siBun,
  siAstro,
  siSvelte,
  siVuedotjs,
  siAngular,
  siGraphql,
  siStripe,
  siCloudflare,
  siJavascript,
  siHtml5,
  siCss,
  siExpress,
  siReactquery,
  siFramer,
  siGreensock,
  siNetlify,
  siPostman,
} from "simple-icons";
import type { SimpleIcon } from "simple-icons";

export const techIconRegistry: Record<string, SimpleIcon> = {
  "Next.js":      siNextdotjs,
  "Tailwind CSS": siTailwindcss,
  "Tailwind":     siTailwindcss,
  "Postgres":     siPostgresql,
  "PostgreSQL":   siPostgresql,
  "Prisma":       siPrisma,
  "Drizzle":      siDrizzle,
  "NeonDB":       siNeon,
  "Neon":         siNeon,
  "DataGrip":     siDatagrip,
  "Cursor":       siCursor,
  "Cursor IDE":   siCursor,
  "TypeScript":   siTypescript,
  "React":        siReact,
  "Node.js":      siNodedotjs,
  "Node":         siNodedotjs,
  "Git":          siGit,
  "GitHub":       siGithub,
  "Vercel":       siVercel,
  "Figma":        siFigma,
  "Supabase":     siSupabase,
  "Firebase":     siFirebase,
  "MongoDB":      siMongodb,
  "Redis":        siRedis,
  "Docker":       siDocker,
  "Python":       siPython,
  "Rust":         siRust,
  "Swift":        siSwift,
  "Kubernetes":   siKubernetes,
  "Linux":        siLinux,
  "Vite":         siVite,
  "Bun":          siBun,
  "Astro":        siAstro,
  "Svelte":       siSvelte,
  "Vue":          siVuedotjs,
  "Vue.js":       siVuedotjs,
  "Angular":      siAngular,
  "GraphQL":      siGraphql,
  "Stripe":           siStripe,
  "Cloudflare":       siCloudflare,
  "JavaScript":       siJavascript,
  "HTML":             siHtml5,
  "HTML5":            siHtml5,
  "CSS":              siCss,
  "CSS3":             siCss,
  "Express":          siExpress,
  "Express.js":       siExpress,
  "TanStack Query":   siReactquery,
  "React Query":      siReactquery,
  "Framer Motion":    siFramer,
  "Framer":           siFramer,
  "GSAP":             siGreensock,
  "GreenSock":        siGreensock,
  "Netlify":          siNetlify,
  "Postman":          siPostman,
};

export function getTechIcon(name: string): SimpleIcon | undefined {
  return techIconRegistry[name];
}

export function getIconColor(icon: SimpleIcon): string {
  // Lighten black icons (#000000 or very dark) so they're visible on dark bg
  const brightness = parseInt(icon.hex, 16);
  return brightness < 0x444444 ? "#ffffff" : `#${icon.hex}`;
}
